# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Build-and-Unit-Tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
   
    - name: Restore dependencies
      run: dotnet restore EShopWebApp/EShopWebApp/EShopWebApp.csproj

    - name: Build
      run: dotnet build EShopWebApp/EShopWebApp/EShopWebApp.csproj --configuration Release

    - name: Run tests
      run: dotnet test EShopWebApp/TestingEShopWebApp.UnitTests/TestingEShopWebApp.UnitTests.csproj --configuration Release
    - name: Publish
      run: dotnet publish EShopWebApp/EShopWebApp/EShopWebApp.csproj --configuration Release --output EShopWebApp/EShopWebApp/bin/Release/net8.0/publish
  
  Deploy-to-Azure:
     
     needs: Build-and-Unit-Tests
     runs-on: ubuntu-latest

     steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Setup .NET
       uses: actions/setup-dotnet@v4
       with:
        dotnet-version: 8.0.x
     - name: Download build artifacts
       uses: actions/download-artifact@v3
       with:
        name: build-artifacts


     - name: 'Login via Az CLI'
       uses: azure/login@v1
       with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

     - name: 'Deploy to Azure Web App'
       uses: azure/webapps-deploy@v2
       with:
        app-name: 'EShopWebAppProject'  
        slot-name: 'production' 
        package: 'EShopWebApp/EShopWebApp/bin/Release/net8.0/publish'
    
   
