# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - EShopWebAppProject

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Restore dependencies
        run: dotnet restore ./EShopWebApp/EShopWebApp/EShopWebApp.csproj
      - name: Build with dotnet
        run: dotnet build --configuration Release ./EShopWebApp/EShopWebApp
      - name: Run unit tests
        run: dotnet test ./EShopWebApp/TestingEShopWebApp.UnitTests/TestingEShopWebApp.UnitTests.csproj --configuration Release --no-build --logger "trx;LogFileName=testresults.trx"  

      - name: dotnet publish
        run: dotnet publish ./EShopWebApp/EShopWebApp
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./EShopWebApp/EShopWebApp

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-unit-test
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C042F1AE27DC4757B74DA49F03DDA73D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_51A80C8516D74D85BCF9358555D59C2F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0EC775323DBD428596143BFB18F4318A }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'EShopWebAppProject'
          slot-name: 'Production'
          package: .
          
